# This file was generated by release.py
require 'formula'
class Pup < Formula
  homepage 'https://github.com/EricChiang/pup'
  version '0.3.6'

  if Hardware.is_64_bit?
    url 'https://github.com/EricChiang/pup/releases/download/v0.3.6/pup_darwin_amd64.zip'
    sha1 '549ce1c7e3ad5ec0129fa46736821676ebb797a1'
  else
    url 'https://github.com/EricChiang/pup/releases/download/v0.3.6/pup_darwin_386.zip'
    sha1 '3738b27bb47bfe4bb7bd682fd93ac8701f323264'
  end

  def install
    bin.install 'pup'
  end
end